### ISSUE TITLE
EPIC: project setup

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/webstore#2]
# Project Development Setup

## Project Info
**Client Name**: Scientist.com

**Project Name**: WebStore

**Repository**: https://gitlab.com/notch8/webstore

**Monitoring/Maintenance/None**?: sentry?

**Slack Channels**: #dev-webstore

## Requirements
- [ ] Dockerize Application (if not Hyku as it's already part of the stack)
- [ ] Lint (Pronto setup in CI: http://playbook-staging.notch8.com/en/dev/install-pronto)
- [x] Test Suite setup locally
- [x] Test suite setup in CI (testing the config is setup properly since tests pass locally)
- [ ] Application setup in CI through to Rancher and you can access the staging url
- [ ] Exception tracking - Sentry
- [ ] Staging (n8 infra)
- [ ] ~~Staging mailer (+ mailtrap.io inbox) - if necessary~~
- [ ] Set the .gitlab-ci.yaml up with build/go pattern so the tests and linting errors do not block a deploy if needed urgently.
- [ ] Add the standard S3 email addresses to the seeds file (rob@notch8.com (super-admin), support@notch8.com (super admin), user@notch8.com (registered user), admin@example.com (admin), user@example.com)
- [X] Hookup the projects merge requests into the merge request slack channel
- [ ] Pin the following info template in the projects internal/dev slack channel:
  - Application Type: (Example: Multi Tenant Hyku Application, Running Hyku off of Main)
  - RepoREADME.md is: (Example: IN PROGRESS of being updated -or- UPDATED)
  - Linting (Example: Setup w/ Green Pipeline -or- Not Setup)
  - Test Suite Setup running in 6 groups in parallel w/ Green Pipeline
  - You cannot push directly to main (http://playbook-staging.notch8.com/en/devops/project-setup/dont-merge-to-main)
- [x] Make bookmarks for the following in the projects internal/dev slack channel:
  - Google Drive Folder: (add link)
  - Gitlab Board: (add link)
  - Staging Url: (add link)
  - Mailtrap Acct un/pw: (add 1Pass link)

**Note**: Each of these steps should be considered its own step. Create a ticket for each.
